//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AH.ModuleController.ADMSSR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BedCharges", Namespace="http://schemas.datacontract.org/2004/07/AH.ADMS.MODEL")]
    [System.SerializableAttribute()]
    public partial class BedCharges : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.BedType BedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.Building BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.Department DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.RevenueHead RevenueHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.RevenueHeadGroup RevenueHeadGroupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.BedType BedType {
            get {
                return this.BedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BedTypeField, value) != true)) {
                    this.BedTypeField = value;
                    this.RaisePropertyChanged("BedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.Building Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.Department Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.RevenueHead RevenueHead {
            get {
                return this.RevenueHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueHeadField, value) != true)) {
                    this.RevenueHeadField = value;
                    this.RaisePropertyChanged("RevenueHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.RevenueHeadGroup RevenueHeadGroup {
            get {
                return this.RevenueHeadGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueHeadGroupField, value) != true)) {
                    this.RevenueHeadGroupField = value;
                    this.RaisePropertyChanged("RevenueHeadGroup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BedType", Namespace="http://schemas.datacontract.org/2004/07/AH.PRMS.MODEL")]
    [System.SerializableAttribute()]
    public partial class BedType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.BedFacility BedFacilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SerialPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleBengField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.BedFacility BedFacility {
            get {
                return this.BedFacilityField;
            }
            set {
                if ((object.ReferenceEquals(this.BedFacilityField, value) != true)) {
                    this.BedFacilityField = value;
                    this.RaisePropertyChanged("BedFacility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SerialPriority {
            get {
                return this.SerialPriorityField;
            }
            set {
                if ((this.SerialPriorityField.Equals(value) != true)) {
                    this.SerialPriorityField = value;
                    this.RaisePropertyChanged("SerialPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleBeng {
            get {
                return this.TitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleBengField, value) != true)) {
                    this.TitleBengField = value;
                    this.RaisePropertyChanged("TitleBeng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/AH.PRMS.MODEL")]
    [System.SerializableAttribute()]
    public partial class Building : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingTitleBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short FloorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SerialNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingID {
            get {
                return this.BuildingIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingIDField, value) != true)) {
                    this.BuildingIDField = value;
                    this.RaisePropertyChanged("BuildingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingTitle {
            get {
                return this.BuildingTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingTitleField, value) != true)) {
                    this.BuildingTitleField = value;
                    this.RaisePropertyChanged("BuildingTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingTitleBeng {
            get {
                return this.BuildingTitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingTitleBengField, value) != true)) {
                    this.BuildingTitleBengField = value;
                    this.RaisePropertyChanged("BuildingTitleBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Floors {
            get {
                return this.FloorsField;
            }
            set {
                if ((this.FloorsField.Equals(value) != true)) {
                    this.FloorsField = value;
                    this.RaisePropertyChanged("Floors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((this.SerialNoField.Equals(value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.DepartmentCategory DepartmentCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.DepartmentGroup DepartmentGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentTitleBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.DepartmentType DepartmentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentUnitHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentUnitHeadIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SerialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.DepartmentCategory DepartmentCategory {
            get {
                return this.DepartmentCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCategoryField, value) != true)) {
                    this.DepartmentCategoryField = value;
                    this.RaisePropertyChanged("DepartmentCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.DepartmentGroup DepartmentGroup {
            get {
                return this.DepartmentGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentGroupField, value) != true)) {
                    this.DepartmentGroupField = value;
                    this.RaisePropertyChanged("DepartmentGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIDField, value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentTitle {
            get {
                return this.DepartmentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentTitleField, value) != true)) {
                    this.DepartmentTitleField = value;
                    this.RaisePropertyChanged("DepartmentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentTitleBeng {
            get {
                return this.DepartmentTitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentTitleBengField, value) != true)) {
                    this.DepartmentTitleBengField = value;
                    this.RaisePropertyChanged("DepartmentTitleBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.DepartmentType DepartmentType {
            get {
                return this.DepartmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentTypeField, value) != true)) {
                    this.DepartmentTypeField = value;
                    this.RaisePropertyChanged("DepartmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentUnit {
            get {
                return this.DepartmentUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentUnitField, value) != true)) {
                    this.DepartmentUnitField = value;
                    this.RaisePropertyChanged("DepartmentUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentUnitHead {
            get {
                return this.DepartmentUnitHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentUnitHeadField, value) != true)) {
                    this.DepartmentUnitHeadField = value;
                    this.RaisePropertyChanged("DepartmentUnitHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentUnitHeadID {
            get {
                return this.DepartmentUnitHeadIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentUnitHeadIDField, value) != true)) {
                    this.DepartmentUnitHeadIDField = value;
                    this.RaisePropertyChanged("DepartmentUnitHeadID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((this.SerialField.Equals(value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntryParameter", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class EntryParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntryByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SysDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateByNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIDField, value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntryBy {
            get {
                return this.EntryByField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryByField, value) != true)) {
                    this.EntryByField = value;
                    this.RaisePropertyChanged("EntryBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDate {
            get {
                return this.EntryDateField;
            }
            set {
                if ((this.EntryDateField.Equals(value) != true)) {
                    this.EntryDateField = value;
                    this.RaisePropertyChanged("EntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntryName {
            get {
                return this.EntryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryNameField, value) != true)) {
                    this.EntryNameField = value;
                    this.RaisePropertyChanged("EntryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIDField, value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineID {
            get {
                return this.MachineIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineIDField, value) != true)) {
                    this.MachineIDField = value;
                    this.RaisePropertyChanged("MachineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SysDate {
            get {
                return this.SysDateField;
            }
            set {
                if ((this.SysDateField.Equals(value) != true)) {
                    this.SysDateField = value;
                    this.RaisePropertyChanged("SysDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateByField, value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateByName {
            get {
                return this.UpdateByNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateByNameField, value) != true)) {
                    this.UpdateByNameField = value;
                    this.RaisePropertyChanged("UpdateByName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevenueHead", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class RevenueHead : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevenueAccountsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.RevenueHeadGroup RevenueHeadGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevenueHeadStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleBengField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevenueAccountsCode {
            get {
                return this.RevenueAccountsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueAccountsCodeField, value) != true)) {
                    this.RevenueAccountsCodeField = value;
                    this.RaisePropertyChanged("RevenueAccountsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.RevenueHeadGroup RevenueHeadGroup {
            get {
                return this.RevenueHeadGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueHeadGroupField, value) != true)) {
                    this.RevenueHeadGroupField = value;
                    this.RaisePropertyChanged("RevenueHeadGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevenueHeadString {
            get {
                return this.RevenueHeadStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueHeadStringField, value) != true)) {
                    this.RevenueHeadStringField = value;
                    this.RaisePropertyChanged("RevenueHeadString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleBeng {
            get {
                return this.TitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleBengField, value) != true)) {
                    this.TitleBengField = value;
                    this.RaisePropertyChanged("TitleBeng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RevenueHeadGroup", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class RevenueHeadGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleBengField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleBeng {
            get {
                return this.TitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleBengField, value) != true)) {
                    this.TitleBengField = value;
                    this.RaisePropertyChanged("TitleBeng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BedFacility", Namespace="http://schemas.datacontract.org/2004/07/AH.PRMS.MODEL")]
    [System.SerializableAttribute()]
    public partial class BedFacility : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AlmirahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CorridorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short FridgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short InternetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MaxAllowedPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short NewspaperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SofaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short VerandaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short WashRoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short XtraBedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short AC {
            get {
                return this.ACField;
            }
            set {
                if ((this.ACField.Equals(value) != true)) {
                    this.ACField = value;
                    this.RaisePropertyChanged("AC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Almirah {
            get {
                return this.AlmirahField;
            }
            set {
                if ((this.AlmirahField.Equals(value) != true)) {
                    this.AlmirahField = value;
                    this.RaisePropertyChanged("Almirah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Corridor {
            get {
                return this.CorridorField;
            }
            set {
                if ((this.CorridorField.Equals(value) != true)) {
                    this.CorridorField = value;
                    this.RaisePropertyChanged("Corridor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Fridge {
            get {
                return this.FridgeField;
            }
            set {
                if ((this.FridgeField.Equals(value) != true)) {
                    this.FridgeField = value;
                    this.RaisePropertyChanged("Fridge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Internet {
            get {
                return this.InternetField;
            }
            set {
                if ((this.InternetField.Equals(value) != true)) {
                    this.InternetField = value;
                    this.RaisePropertyChanged("Internet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MaxAllowedPerson {
            get {
                return this.MaxAllowedPersonField;
            }
            set {
                if ((this.MaxAllowedPersonField.Equals(value) != true)) {
                    this.MaxAllowedPersonField = value;
                    this.RaisePropertyChanged("MaxAllowedPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Newspaper {
            get {
                return this.NewspaperField;
            }
            set {
                if ((this.NewspaperField.Equals(value) != true)) {
                    this.NewspaperField = value;
                    this.RaisePropertyChanged("Newspaper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Sofa {
            get {
                return this.SofaField;
            }
            set {
                if ((this.SofaField.Equals(value) != true)) {
                    this.SofaField = value;
                    this.RaisePropertyChanged("Sofa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TV {
            get {
                return this.TVField;
            }
            set {
                if ((this.TVField.Equals(value) != true)) {
                    this.TVField = value;
                    this.RaisePropertyChanged("TV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleBeng {
            get {
                return this.TitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleBengField, value) != true)) {
                    this.TitleBengField = value;
                    this.RaisePropertyChanged("TitleBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Veranda {
            get {
                return this.VerandaField;
            }
            set {
                if ((this.VerandaField.Equals(value) != true)) {
                    this.VerandaField = value;
                    this.RaisePropertyChanged("Veranda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short WashRoom {
            get {
                return this.WashRoomField;
            }
            set {
                if ((this.WashRoomField.Equals(value) != true)) {
                    this.WashRoomField = value;
                    this.RaisePropertyChanged("WashRoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short XtraBed {
            get {
                return this.XtraBedField;
            }
            set {
                if ((this.XtraBedField.Equals(value) != true)) {
                    this.XtraBedField = value;
                    this.RaisePropertyChanged("XtraBed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/AH.PRMS.MODEL")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SloganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SloganBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressBeng {
            get {
                return this.AddressBengField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressBengField, value) != true)) {
                    this.AddressBengField = value;
                    this.RaisePropertyChanged("AddressBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogoPath {
            get {
                return this.LogoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoPathField, value) != true)) {
                    this.LogoPathField = value;
                    this.RaisePropertyChanged("LogoPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameBeng {
            get {
                return this.NameBengField;
            }
            set {
                if ((object.ReferenceEquals(this.NameBengField, value) != true)) {
                    this.NameBengField = value;
                    this.RaisePropertyChanged("NameBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNos {
            get {
                return this.PhoneNosField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNosField, value) != true)) {
                    this.PhoneNosField = value;
                    this.RaisePropertyChanged("PhoneNos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Slogan {
            get {
                return this.SloganField;
            }
            set {
                if ((object.ReferenceEquals(this.SloganField, value) != true)) {
                    this.SloganField = value;
                    this.RaisePropertyChanged("Slogan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SloganBeng {
            get {
                return this.SloganBengField;
            }
            set {
                if ((object.ReferenceEquals(this.SloganBengField, value) != true)) {
                    this.SloganBengField = value;
                    this.RaisePropertyChanged("SloganBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSiteAddress {
            get {
                return this.WebSiteAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteAddressField, value) != true)) {
                    this.WebSiteAddressField = value;
                    this.RaisePropertyChanged("WebSiteAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/AH.PRMS.MODEL")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationTitleBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressBeng {
            get {
                return this.AddressBengField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressBengField, value) != true)) {
                    this.AddressBengField = value;
                    this.RaisePropertyChanged("AddressBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIDField, value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationTitle {
            get {
                return this.LocationTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTitleField, value) != true)) {
                    this.LocationTitleField = value;
                    this.RaisePropertyChanged("LocationTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationTitleBeng {
            get {
                return this.LocationTitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTitleBengField, value) != true)) {
                    this.LocationTitleBengField = value;
                    this.RaisePropertyChanged("LocationTitleBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNos {
            get {
                return this.PhoneNosField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNosField, value) != true)) {
                    this.PhoneNosField = value;
                    this.RaisePropertyChanged("PhoneNos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((this.SerialField.Equals(value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebAddress {
            get {
                return this.WebAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.WebAddressField, value) != true)) {
                    this.WebAddressField = value;
                    this.RaisePropertyChanged("WebAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentCategory", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class DepartmentCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentCategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentCategoryTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentCategoryTitleBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.DepartmentType DepartmentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentCategoryID {
            get {
                return this.DepartmentCategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCategoryIDField, value) != true)) {
                    this.DepartmentCategoryIDField = value;
                    this.RaisePropertyChanged("DepartmentCategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentCategoryTitle {
            get {
                return this.DepartmentCategoryTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCategoryTitleField, value) != true)) {
                    this.DepartmentCategoryTitleField = value;
                    this.RaisePropertyChanged("DepartmentCategoryTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentCategoryTitleBeng {
            get {
                return this.DepartmentCategoryTitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCategoryTitleBengField, value) != true)) {
                    this.DepartmentCategoryTitleBengField = value;
                    this.RaisePropertyChanged("DepartmentCategoryTitleBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.DepartmentType DepartmentType {
            get {
                return this.DepartmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentTypeField, value) != true)) {
                    this.DepartmentTypeField = value;
                    this.RaisePropertyChanged("DepartmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentGroup", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class DepartmentGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.DepartmentCategory DepartmentCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentGroupTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentGroupTitleBengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.DepartmentType DepartmentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AH.ModuleController.ADMSSR.EntryParameter EntryParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SerialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.DepartmentCategory DepartmentCategory {
            get {
                return this.DepartmentCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentCategoryField, value) != true)) {
                    this.DepartmentCategoryField = value;
                    this.RaisePropertyChanged("DepartmentCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentGroupID {
            get {
                return this.DepartmentGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentGroupIDField, value) != true)) {
                    this.DepartmentGroupIDField = value;
                    this.RaisePropertyChanged("DepartmentGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentGroupTitle {
            get {
                return this.DepartmentGroupTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentGroupTitleField, value) != true)) {
                    this.DepartmentGroupTitleField = value;
                    this.RaisePropertyChanged("DepartmentGroupTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentGroupTitleBeng {
            get {
                return this.DepartmentGroupTitleBengField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentGroupTitleBengField, value) != true)) {
                    this.DepartmentGroupTitleBengField = value;
                    this.RaisePropertyChanged("DepartmentGroupTitleBeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.DepartmentType DepartmentType {
            get {
                return this.DepartmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentTypeField, value) != true)) {
                    this.DepartmentTypeField = value;
                    this.RaisePropertyChanged("DepartmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentTypeID {
            get {
                return this.DepartmentTypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentTypeIDField, value) != true)) {
                    this.DepartmentTypeIDField = value;
                    this.RaisePropertyChanged("DepartmentTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AH.ModuleController.ADMSSR.EntryParameter EntryParameter {
            get {
                return this.EntryParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.EntryParameterField, value) != true)) {
                    this.EntryParameterField = value;
                    this.RaisePropertyChanged("EntryParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((this.SerialField.Equals(value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentType", Namespace="http://schemas.datacontract.org/2004/07/AH.Shared.MODEL")]
    [System.SerializableAttribute()]
    public partial class DepartmentType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeID {
            get {
                return this.TypeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeIDField, value) != true)) {
                    this.TypeIDField = value;
                    this.RaisePropertyChanged("TypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeTitle {
            get {
                return this.TypeTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeTitleField, value) != true)) {
                    this.TypeTitleField = value;
                    this.RaisePropertyChanged("TypeTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ADMSSR.IADMSWS")]
    public interface IADMSWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/SaveBedFee", ReplyAction="http://tempuri.org/IADMSWS/SaveBedFeeResponse")]
        short SaveBedFee(AH.ModuleController.ADMSSR.BedCharges tbd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/SaveBedFee", ReplyAction="http://tempuri.org/IADMSWS/SaveBedFeeResponse")]
        System.Threading.Tasks.Task<short> SaveBedFeeAsync(AH.ModuleController.ADMSSR.BedCharges tbd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/UpdateBedFee", ReplyAction="http://tempuri.org/IADMSWS/UpdateBedFeeResponse")]
        short UpdateBedFee(AH.ModuleController.ADMSSR.BedCharges ubd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/UpdateBedFee", ReplyAction="http://tempuri.org/IADMSWS/UpdateBedFeeResponse")]
        System.Threading.Tasks.Task<short> UpdateBedFeeAsync(AH.ModuleController.ADMSSR.BedCharges ubd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedRateShow", ReplyAction="http://tempuri.org/IADMSWS/GetBedRateShowResponse")]
        AH.ModuleController.ADMSSR.BedCharges[] GetBedRateShow(string bedtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedRateShow", ReplyAction="http://tempuri.org/IADMSWS/GetBedRateShowResponse")]
        System.Threading.Tasks.Task<AH.ModuleController.ADMSSR.BedCharges[]> GetBedRateShowAsync(string bedtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/VerifyBedTestFee", ReplyAction="http://tempuri.org/IADMSWS/VerifyBedTestFeeResponse")]
        int VerifyBedTestFee(string bedtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/VerifyBedTestFee", ReplyAction="http://tempuri.org/IADMSWS/VerifyBedTestFeeResponse")]
        System.Threading.Tasks.Task<int> VerifyBedTestFeeAsync(string bedtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedtypeDict", ReplyAction="http://tempuri.org/IADMSWS/GetBedtypeDictResponse")]
        System.Collections.Generic.Dictionary<string, string> GetBedtypeDict(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedtypeDict", ReplyAction="http://tempuri.org/IADMSWS/GetBedtypeDictResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBedtypeDictAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBuildingDict", ReplyAction="http://tempuri.org/IADMSWS/GetBuildingDictResponse")]
        System.Collections.Generic.Dictionary<string, string> GetBuildingDict(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBuildingDict", ReplyAction="http://tempuri.org/IADMSWS/GetBuildingDictResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBuildingDictAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedRates", ReplyAction="http://tempuri.org/IADMSWS/GetBedRatesResponse")]
        AH.ModuleController.ADMSSR.BedCharges[] GetBedRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedRates", ReplyAction="http://tempuri.org/IADMSWS/GetBedRatesResponse")]
        System.Threading.Tasks.Task<AH.ModuleController.ADMSSR.BedCharges[]> GetBedRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedRateSetup", ReplyAction="http://tempuri.org/IADMSWS/GetBedRateSetupResponse")]
        AH.ModuleController.ADMSSR.BedCharges[] GetBedRateSetup(string bedtype, string headgroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADMSWS/GetBedRateSetup", ReplyAction="http://tempuri.org/IADMSWS/GetBedRateSetupResponse")]
        System.Threading.Tasks.Task<AH.ModuleController.ADMSSR.BedCharges[]> GetBedRateSetupAsync(string bedtype, string headgroup);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IADMSWSChannel : AH.ModuleController.ADMSSR.IADMSWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADMSWSClient : System.ServiceModel.ClientBase<AH.ModuleController.ADMSSR.IADMSWS>, AH.ModuleController.ADMSSR.IADMSWS {
        
        public ADMSWSClient() {
        }
        
        public ADMSWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADMSWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADMSWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADMSWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short SaveBedFee(AH.ModuleController.ADMSSR.BedCharges tbd) {
            return base.Channel.SaveBedFee(tbd);
        }
        
        public System.Threading.Tasks.Task<short> SaveBedFeeAsync(AH.ModuleController.ADMSSR.BedCharges tbd) {
            return base.Channel.SaveBedFeeAsync(tbd);
        }
        
        public short UpdateBedFee(AH.ModuleController.ADMSSR.BedCharges ubd) {
            return base.Channel.UpdateBedFee(ubd);
        }
        
        public System.Threading.Tasks.Task<short> UpdateBedFeeAsync(AH.ModuleController.ADMSSR.BedCharges ubd) {
            return base.Channel.UpdateBedFeeAsync(ubd);
        }
        
        public AH.ModuleController.ADMSSR.BedCharges[] GetBedRateShow(string bedtype) {
            return base.Channel.GetBedRateShow(bedtype);
        }
        
        public System.Threading.Tasks.Task<AH.ModuleController.ADMSSR.BedCharges[]> GetBedRateShowAsync(string bedtype) {
            return base.Channel.GetBedRateShowAsync(bedtype);
        }
        
        public int VerifyBedTestFee(string bedtype) {
            return base.Channel.VerifyBedTestFee(bedtype);
        }
        
        public System.Threading.Tasks.Task<int> VerifyBedTestFeeAsync(string bedtype) {
            return base.Channel.VerifyBedTestFeeAsync(bedtype);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetBedtypeDict(string type) {
            return base.Channel.GetBedtypeDict(type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBedtypeDictAsync(string type) {
            return base.Channel.GetBedtypeDictAsync(type);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetBuildingDict(string type) {
            return base.Channel.GetBuildingDict(type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetBuildingDictAsync(string type) {
            return base.Channel.GetBuildingDictAsync(type);
        }
        
        public AH.ModuleController.ADMSSR.BedCharges[] GetBedRates() {
            return base.Channel.GetBedRates();
        }
        
        public System.Threading.Tasks.Task<AH.ModuleController.ADMSSR.BedCharges[]> GetBedRatesAsync() {
            return base.Channel.GetBedRatesAsync();
        }
        
        public AH.ModuleController.ADMSSR.BedCharges[] GetBedRateSetup(string bedtype, string headgroup) {
            return base.Channel.GetBedRateSetup(bedtype, headgroup);
        }
        
        public System.Threading.Tasks.Task<AH.ModuleController.ADMSSR.BedCharges[]> GetBedRateSetupAsync(string bedtype, string headgroup) {
            return base.Channel.GetBedRateSetupAsync(bedtype, headgroup);
        }
    }
}
